### PR TITLE
Get initial time step to converge and Modernize repo

### PR DESCRIPTION
**Pull request by lindsayad**
In optimized mode, floating point exception catching is optimized out; that's why you can run without errors in `opt` mode. In `dbg` mode, `FPE` exceptions will be thrown and there's no way to circumvent them other than to ensure that they don't occur. Consequently you have to find an initial time step for which no `FPE`s are generated. This generally corresponds to a time step for which your non-linear iterations actually converge. Running in `opt` mode I saw that this happened for a time step of `.004096` (both larger and smaller steps may lead to non-convergence) so I modified `dt` in your input file such that in `dbg` mode you won't get floating point exceptions during that initial time step (and perhaps not even during later time steps).

Additionally, I've merged in the `shannon-lab/devel` branch because it's actually up-to-date with current MOOSE specifications, e.g. the C++ files are properly formatted and most importantly `zapdos` will actually run with the current MOOSE `HEAD`. Your current development branch will not run with an up-to-date MOOSE because you're missing a lot of MOOSE includes in your source files.

Within this merge is the addition of a submodule `squirrel`. If you merge this pull request, you will need to run:
```
git submodule init
git submodule update
```
and then compile.

Also to ensure that any new C++ code you write meets formatting specifications, I encourage you to run
```
./scripts/install_format_hook.sh
```
after merging this PR. It's a totally automated process and shouldn't cause any headaches.

### CODE REVIEW

**Comment by jhaase1** [comment]
Alex,

I'm getting the error

~/projects/zapdos/squirrel/include/kernels/ConservativeTemperatureAdvection.h:4:35:
fatal error: ConservativeAdvection.h: No such file or directory
 #include "ConservativeAdvection.h"

Could you include that?

Regards,

John R. Haase
jhaase1@nd.edu

**Comment by lindsayad** [comment]
It looks like you're going to have to update your MOOSE because MOOSE 
now has the ConservativeAdvection class within its 
framework/src(include)/kernels directory. Sorry!

**Comment by jhaase1** [comment]
Thanks Alex,

I went back and ran the commands

cd ~/projects/moose
git fetch origin
git rebase origin/master

Then started compiling ... and I got the error below. Any suggestions?

/afs/
crc.nd.edu/user/j/jhaase1/ZapdosDir//moose//framework/src/geomsearch/NearestNodeLocator.C:
In member function ‘void NearestNodeLocator::findNodes()’:
/afs/
crc.nd.edu/user/j/jhaase1/ZapdosDir//moose//framework/src/geomsearch/NearestNodeLocator.C:96:7:
error: ‘BoundingBox’ was not declared in this scope
       BoundingBox my_box = MeshTools::create_local_bounding_box(_mesh);
       ^~~~~~~~~~~
/afs/
crc.nd.edu/user/j/jhaase1/ZapdosDir//moose//framework/src/geomsearch/NearestNodeLocator.C:96:7:
note: suggested alternative:
In file included from /afs/
crc.nd.edu/user/j/jhaase1/ZapdosDir//moose//framework/include/mesh/MooseMesh.h:30:0
,
                 from /afs/
crc.nd.edu/user/j/jhaase1/ZapdosDir//moose//framework/src/geomsearch/NearestNodeLocator.C:16
:
/afs/
crc.nd.edu/user/j/jhaase1/ZapdosDir/moose/scripts/../libmesh/installed/include/libmesh/mesh_tools.h:64:7:
note:   ‘libMesh::MeshTools::BoundingBox’
 class BoundingBox : public std::pair<Point, Point>
       ^~~~~~~~~~~
/afs/
crc.nd.edu/user/j/jhaase1/ZapdosDir//moose//framework/src/geomsearch/NearestNodeLocator.C:110:58:
error: ‘my_box’ was not declared in this scope
       my_inflated_box = new MeshTools::BoundingBox(Point(my_box.first(0) -
distance_x,
                                                          ^~~~~~
make: *** [/afs/
crc.nd.edu/user/j/jhaase1/ZapdosDir//moose//framework/src/geomsearch/NearestNodeLocator.x86_64-unknown-linux-gnu.opt.lo]
Error 1

Regards,

John R. Haase
jhaase1@nd.edu

**Comment by lindsayad** [comment]
It's a never ending rabbit hole for you today :-( BoundingBox was 
recently modified in libmesh. You're going to have to run the 
`update_and_rebuild_libmesh` script in the moose scripts directory. I 
recommend doing:

export METHODS="opt dbg"

before running that script if you never use the oprof mode (I don't). 
That'll save you 1/3 of the libmesh build time.

Alex

**Comment by jhaase1** [comment]
Yeah, I've just had a week ...

Thank you very much

Regards,

John R. Haase
jhaase1@nd.edu

**Pull request merged**
